### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by jcbriones** [okta/okta-storage-swift#24]
Please try to add an SPM support for this package. This will be helpful for those who aren't using Cocoapods. Thank you

**Comment by laura-rodriguez** [comment]
Hi @jcbriones,

Thanks for your feedback. Our Mobile engineers will review your issue and get back to you.

**Comment by mikenachbaur-okta** [comment]
Hi @jcbriones, I agree with you, SPM support would be great. We've been implementing support incrementally to each of our Swift repos, and haven't gotten to this one yet. 

I'll make sure to track this, and will update this issue with our progress.

**Comment by oleggnidets-okta** [comment]
Hi @jcbriones @miketraverso 
It's on master now. Please, let us know whether it works for you.
Thanks!

**Comment by miketraverso** [comment]
Using ...

```
 .package(name: "OktaOidc", url: "https://github.com/okta/okta-oidc-ios.git", from: "3.9.2"),
 .package(name: "OktaStorage", url: "https://github.com/okta/okta-storage-swift.git", from: "1.1.1")
```

I'm still seeing:

```
 https://github.com/okta/okta-storage-swift.git has no Package.swift manifest for version 1.1.1 in https://github.com/okta/okta-storage-swift.git
```

Perhaps a version bump is warranted here with this change?

**Comment by mikenachbaur-okta** [comment]
Yes @miketraverso, we haven't tagged a release for this yet. You can try this out now by using `.branch("master")` instead of the version number. I'll be pushing a release shortly though.

**Comment by mikenachbaur-okta** [comment]
@miketraverso Version 1.1.2 has been released, which should include support for Swift Package Manager. Please give that a try, and see if it works for you.

And thank you for your feature request!
